<x-app-layout>
<div class="gpha-page-shell space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="font-extrabold text-gpha-primary">Operations Logs</p><h1 class="text-3xl font-black text-slate-950">Edit Activity</h1></div><a href="{{ route('ems.activities.show',$activity) }}" class="gpha-button-primary">Close</a></div>
    @if($errors->any())<x-dismissible-alert type="error"><p class="font-extrabold">Please correct the following:</p><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-dismissible-alert>@endif
    <section class="gpha-panel p-5"><form method="POST" action="{{ route('ems.activities.update',$activity) }}" class="space-y-5" x-data="{followUp:@js((bool)old('requires_follow_up',$activity->requires_follow_up)),outcomeOpen:@js(filled(old('outcome',$activity->outcome)))}">@csrf @method('PUT')
        <div class="grid gap-4 md:grid-cols-2">
            <label><span class="gpha-label">Activity Date <span class="text-red-600">*</span></span><input type="date" name="activity_date" value="{{ old('activity_date',$activity->activity_date->toDateString()) }}" max="{{ today()->toDateString() }}" class="gpha-input" required></label>
            <label><span class="gpha-label">Category <span class="text-red-600">*</span></span><select name="category" class="gpha-input" required>@foreach(['operations','meeting','training','inspection','administration','outreach'] as $category)<option value="{{ $category }}" @selected(old('category',$activity->category)===$category)>{{ str($category)->headline() }}</option>@endforeach</select></label>
            <div class="md:col-span-2"><span class="gpha-label">What happened? <span class="text-red-600">*</span></span><x-ems.rich-text-editor name="description" :value="old('description',$activity->description)" placeholder="Briefly describe the activity" required /></div>
            <div class="flex flex-wrap items-center gap-5 md:col-span-2"><button type="button" @click="outcomeOpen=!outcomeOpen" class="gpha-button-secondary" x-text="outcomeOpen?'Hide Outcome':'Add Outcome / Decision'"></button><label class="flex items-center gap-3"><input type="checkbox" name="requires_follow_up" value="1" x-model="followUp"><span class="font-extrabold">Requires follow-up</span></label></div>
            <div x-cloak x-show="outcomeOpen" x-transition class="md:col-span-2"><span class="gpha-label">Outcome / Decision</span><x-ems.rich-text-editor name="outcome" :value="old('outcome',$activity->outcome)" placeholder="Record the outcome or decision" /></div>
        </div>
        <div x-cloak x-show="followUp" x-transition class="grid gap-4 rounded-xl border border-amber-200 bg-amber-50 p-4 md:grid-cols-3"><label><span class="gpha-label">Follow-up Action <span class="text-red-600">*</span></span><input name="follow_up_action" value="{{ old('follow_up_action',$activity->follow_up_action) }}" class="gpha-input" :required="followUp" maxlength="2000"></label><label><span class="gpha-label">Action Owner <span class="text-red-600">*</span></span><input name="follow_up_owner" value="{{ old('follow_up_owner',$activity->follow_up_owner) }}" class="gpha-input" :required="followUp" maxlength="160"></label><label><span class="gpha-label">Due Date</span><input type="date" name="follow_up_due_date" value="{{ old('follow_up_due_date',$activity->follow_up_due_date?->toDateString()) }}" class="gpha-input"></label></div>
        <div class="flex justify-end gap-2"><a href="{{ route('ems.activities.show',$activity) }}" class="gpha-button-secondary">Cancel</a><button class="gpha-button-primary">Save Changes</button></div>
    </form></section>
</div>
</x-app-layout>
