<x-app-layout>
<div class="gpha-page-shell space-y-6">
    <div class="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p class="font-extrabold text-gpha-primary">Emergency Operations Centre</p><h1 class="mt-1 text-3xl font-black tracking-tight text-slate-950">Operational Overview</h1></div><div class="flex gap-2"><a href="{{ route('ems.dispatches',['new'=>1]) }}" class="gpha-button-primary">Add Movement</a><a href="{{ route('ems.reports') }}" class="gpha-button-secondary">View Reports</a></div></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div class="gpha-metric"><p class="font-bold text-slate-500">Ambulances Available</p><p class="mt-2 text-3xl font-black text-slate-950">{{ $ambulances->where('status','available')->count() }} <span class="text-base text-slate-400">/ {{ $ambulances->count() }}</span></p></div>
        <div class="gpha-metric"><p class="font-bold text-slate-500">Active Movements</p><p class="mt-2 text-3xl font-black text-gpha-primary">{{ $activeDispatches->count() }}</p></div>
        <div class="gpha-metric"><p class="font-bold text-slate-500">Completed Today</p><p class="mt-2 text-3xl font-black text-emerald-700">{{ $completedToday }}</p></div>
        <div class="gpha-metric"><p class="font-bold text-slate-500">Critical Active</p><p class="mt-2 text-3xl font-black {{ $criticalActive?'text-red-600':'text-slate-950' }}">{{ $criticalActive }}</p></div>
    </div>
    <div class="grid gap-6 xl:grid-cols-[1.4fr_1fr]">
        <section class="gpha-panel overflow-hidden"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 class="text-xl font-black">Recent Movements</h2><a href="{{ route('ems.dispatches') }}" class="font-extrabold text-gpha-primary">View All</a></div><div class="overflow-x-auto"><table class="gpha-table"><thead><tr><th>Reference</th><th>Ambulance</th><th>Route</th><th>Priority</th><th>Status</th></tr></thead><tbody>@forelse($recentDispatches as $dispatch)<tr><td><a href="{{ route('ems.dispatches.show',$dispatch) }}" class="font-extrabold text-gpha-primary hover:underline">{{ $dispatch->reference }}</a></td><td>{{ $dispatch->ambulance->fleet_number }}</td><td>{{ $dispatch->origin }} → {{ $dispatch->destination }}</td><td><x-ems.status-badge :status="$dispatch->priority" /></td><td><x-ems.status-badge :status="$dispatch->status" /></td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-500">No movements recorded yet.</td></tr>@endforelse</tbody></table></div></section>
        <section class="gpha-panel p-5"><div class="flex items-center justify-between"><h2 class="text-xl font-black">Fleet Readiness</h2><a href="{{ route('ems.ambulances') }}" class="font-extrabold text-gpha-primary">Manage</a></div><div class="mt-4 space-y-3">@forelse($ambulances as $ambulance)<a href="{{ route('ems.ambulances.show',$ambulance) }}" class="flex items-center justify-between rounded-xl border border-slate-200 p-3 hover:border-gpha-primary"><div><p class="font-extrabold">{{ $ambulance->fleet_number }}</p><p class="font-semibold text-slate-500">{{ $ambulance->registration_number }} · {{ $ambulance->current_location ?: $ambulance->base_location }}</p></div><x-ems.status-badge :status="$ambulance->status" /></a>@empty<p class="text-slate-500">Add ambulances to begin readiness monitoring.</p>@endforelse</div></section>
    </div>
</div>
</x-app-layout>
